---
config:
  layout: elk
  theme: redux
  look: neo
---

flowchart LR

%% Generation 1 (Root)
A1[धनाजी]


%% Generation 2
A1[धनाजी] --> B1[येसाजी]
A1[धनाजी] --> B2[अप्पाजी]


%% Generation 3
B1[येसाजी] --> C1[नारोजी]
B1[येसाजी] --> C2[धनाजी]
B1[येसाजी] --> C3[संताजी]
B1[येसाजी] --> C4[आत्माजी]

B2[अप्पाजी] --> C5[सदोजी]
B2[अप्पाजी] --> C6[त्रिंबकजी]


%% Generation 4
C1[नारोजी] --> D1[गोंदजी]

C2[धनाजी] --> D2[न्हानजी]

C3[संताजी] --> D3[कृष्णाजी]
C3[संताजी] --> D4[विठोजी]

C4[आत्माजी] --> D5[भगवान]

C5[सदोजी] --> D6[रामजी]
C5[सदोजी] --> D7[गोपाळ]

C6[त्रिंबकजी] --> D8[अप्पाजी]


%% Generation 5
D1[गोंदजी] --> E1[उमाजी]

D2[न्हानजी] --> E2[धनाजी]

D3[कृष्णाजी] --> E3[तातोजी]

D4[विठोजी] --> E4[जयराम]

D5[भगवान] --> E5[आत्माजी]

D6[रामजी] --> E6[सावजी]

D7[गोपाळ] --> E7[लक्ष्मण]


%% Generation 6
E1[उमाजी] --> F1[धोंडजी]

E2[धनाजी] --> F2[आबा]

E3[तातोजी] --> F3[भाऊ]
E3[तातोजी] --> F4[दिपाजी]

E4[जयराम] --> F5[नाना]
E4[जयराम] --> F6[राघोजी]
E4[जयराम] --> F7[धकला]
E4[जयराम] --> F8[रत्नाजी]

E5[आत्माजी] --> F9[बाबाजी]
E5[आत्माजी] --> F10[अनाजी]

E6[सावजी] --> F11[विश्वास]
E6[सावजी] --> F12[महादू]

E7[लक्ष्मण] --> F13[विसवा]


%% Generation 7
F1[धोंडजी] --> G1[गोविंद]
F1[धोंडजी] --> G2[नारायण]
F1[धोंडजी] --> G3[जिवाजी]
F1[धोंडजी] --> G4[गोपाळ]
F1[धोंडजी] --> G5[बाळाजी]
F1[धोंडजी] --> G6[पुतळाजी]

F2[आबा] --> G7[धनाजी]
F2[आबा] --> G8[त्रिंबक]
F2[आबा] --> G9[अण्णा]
F2[आबा] --> G10[दिनकर]
F2[आबा] --> G11[सिताराम]

F4[दिपाजी] --> G12[लाडू]

F5[नाना] --> G13[सदाशिव]
F5[नाना] --> G14[शिवराम]

F6[राघोजी] --> G15[रामचंद्र]
F6[राघोजी] --> G16[महादेव]
F6[राघोजी] --> G17[तातोजी]
F6[राघोजी] --> G18[दाजी]

F7[धकला] --> G19[विठोबा]
F7[धकला] --> G20[बाबला]

F8[रत्नाजी] --> G21["महादेव (दत्तक)"]

F9[बाबाजी] --> G22[गंगोजी]

F10[अनाजी] --> G23["सीताराम (झिमजी)"]
F10[अनाजी] --> G24[बाबला]

F13[विसवा] --> G25[उमाजी]


%% Generation 8
G2[नारायण] --> H1[धोंडूजी]

G3[जिवाजी] --> H2[यशवंत]

G4[गोपाळ] --> H3[बाबी]
G4[गोपाळ] --> H4[रामचंद्र]
G4[गोपाळ] --> H5[शंकर]
G4[गोपाळ] --> H6[रावजी]

G6[पुतळाजी] --> H7[गोविंद]
G6[पुतळाजी] --> H8[नारायण]

G7[धनाजी] --> H9[केशव]
G7[धनाजी] --> H10[बाबी]
G7[धनाजी] --> H11[वाघोजी]

G9[अण्णा] --> H12[आबा]
G9[अण्णा] --> H13[गणपत]
G9[अण्णा] --> H14[परशुराम]

G10[दिनकर] --> H15[कृष्णा]

G12[लाडू] --> H16[तातोजी]
G12[लाडू] --> H17[भाऊ]
G12[लाडू] --> H18[दिनकर]

G13[सदाशिव] --> H19[सखाराम]

G14[शिवराम] --> H20[कृष्णा]

G16[महादेव] --> H21[तुकाराम]
G16[महादेव] --> H22[आत्माराम]

G17[तातोजी] --> H23[रामचंद्र]
G17[तातोजी] --> H24[दौलत]
G17[तातोजी] --> H25[गंगाराम]

G18[दाजी] --> H26[शंकर]

G19[विठोबा] --> H27[भिकाजी]

G20[बाबला] --> H28[कृष्णा]
G20[बाबला] --> H29[पुंडलिक]

G22[गंगोजी] --> H30[बाबाजी]
G22[गंगोजी] --> H31[आत्माजी]

G23["सीताराम (झिमजी)"] --> H32[बाबाजी]
G23["सीताराम (झिमजी)"] --> H33[धोंडू]

G25[उमाजी] --> H34[लक्ष्मण]
G25[उमाजी] --> H35[दत्तात्रय]
G25[उमाजी] --> H36[तुकाराम]


%% Generation 9
H2[यशवंत] --> I1[राजाराम]
H2[यशवंत] --> I2[चंद्रकांत]

H5[शंकर] --> I3[धोंडूजी]
H5[शंकर] --> I4[सिताराम]
H5[शंकर] --> I5[रावजी]
H5[शंकर] --> I6[कृष्णकांत]
H5[शंकर] --> I7[अनिल]
H5[शंकर] --> I8[गोपाळ]

H8[नारायण] --> I9[शिवाजी]
H8[नारायण] --> I10[श्रीकांत]
H8[नारायण] --> I11[गोविंद]
H8[नारायण] --> I12[पुतळाजी]

H9[केशव] --> I13[भिकाजी]

H10[बाबी] --> I14[शंकर]

H12[आबा] --> I15[पंडित]
H12[आबा] --> I16[सदाशिव]

H13[गणपत] --> I17[काशिनाथ]

H15[कृष्णा] --> I18[दिनकर]
H15[कृष्णा] --> I19[विष्णू]
H15[कृष्णा] --> I20[विलास]

H17[भाऊ] --> I21[दिपाजी]

H18[दिनकर] --> I22[भाऊ]
H18[दिनकर] --> I23[राजाराम]

H19[सखाराम] --> I24[बाळकृष्ण]

H20[कृष्णा] --> I25[शिवाजी]
H20[कृष्णा] --> I26[नारायण]

H21[तुकाराम] --> I27[वसंत]

H23[रामचंद्र] --> I28[अंकुश]
H23[रामचंद्र] --> I29[दत्ताराम]
H23[रामचंद्र] --> I30[बाळकृष्ण]

H26[शंकर] --> I31[राघोजी]

H27[भिकाजी] --> I32[वामन]

H28[कृष्णा] --> I33[सखाराम]

H29[पुंडलिक] --> I34[सिताराम]

H30[बाबाजी] --> I35[सखाराम]
H30[बाबाजी] --> I36[तुकाराम]

H32[बाबाजी] --> I37[शांताराम]
H32[बाबाजी] --> I38[काशीराम]
H32[बाबाजी] --> I39[आकाराम]
H32[बाबाजी] --> I40[दत्तात्रय]
H32[बाबाजी] --> I41[सिताराम]

H34[लक्ष्मण] --> I42[राजाराम]
H34[लक्ष्मण] --> I43[विजय]

H35[दत्तात्रय] --> I44[मनोहर]

H36[तुकाराम] --> I45[संभाजी]
H36[तुकाराम] --> I46[रमेश]
H36[तुकाराम] --> I47[सुरेश]


%% Generation 10
I1[राजाराम] --> J1[प्रकाश]

I2[चंद्रकांत] --> J2[किशोर]
I2[चंद्रकांत] --> J3[उपेश]

I3[धोंडूजी] --> J4[मनोहर]
I3[धोंडूजी] --> J5[सुभाष]
I3[धोंडूजी] --> J6[दिनेश]

I4[सिताराम] --> J7[रमेश]

I5[रावजी] --> J8[प्रकाश]

I6[कृष्णकांत] --> J9[प्रदीप]
I6[कृष्णकांत] --> J10[नितीन]
I6[कृष्णकांत] --> J11[अभिजीत]

I7[अनिल] --> J12[प्रशांत]
I7[अनिल] --> J13[नविन]

I8[गोपाळ] --> J14[सुशील]
I8[गोपाळ] --> J15[संतोष]

I9[शिवाजी] --> J16[दिगंबर]
I9[शिवाजी] --> J17[जयप्रकाश]
I9[शिवाजी] --> J18[विकास]

I10[श्रीकांत] --> J19[प्रशांत]
I10[श्रीकांत] --> J20[उन्मेश]

I11[गोविंद] --> J21[सुधांशु]

I12[पुतळाजी] --> J22[नितीन]

I14[शंकर] --> J23[प्रभाकर]
I14[शंकर] --> J24[विलास]

I17[काशिनाथ] --> J25[प्रकाश]
I17[काशिनाथ] --> J26[संतोष]

I18[दिनकर] --> J27[मंदार]

I19[विष्णू] --> J28[प्रशांत]

I20[विलास] --> J29[संकेत]
I20[विलास] --> J30[साईल]

I21[दिपाजी] --> J31[अनंत]
I21[दिपाजी] --> J32[अजय]

I22[भाऊ] --> J33[दिनेश]

I23[राजाराम] --> J34[हर्षद]
I23[राजाराम] --> J35[सागर]

I24[बाळकृष्ण] --> J36[प्रभाकर]
I24[बाळकृष्ण] --> J37[रामकृष्ण]
I24[बाळकृष्ण] --> J38[श्रीकृष्ण]
I24[बाळकृष्ण] --> J39[हरिकृष्ण]

I27[वसंत] --> J40[दीपक]
I27[वसंत] --> J41[संजय]
I27[वसंत] --> J42[विलास]

I28[अंकुश] --> J43[सतिश]
I28[अंकुश] --> J44[प्रमोद]

I29[दत्ताराम] --> J45[शशिकांत]

I30[बाळकृष्ण] --> J46[प्रविण]
I30[बाळकृष्ण] --> J47[अविनाश]
I30[बाळकृष्ण] --> J48[चंद्रशेखर]

I31[राघोजी] --> J49[दिलीप]
I31[राघोजी] --> J50[शरद]
I31[राघोजी] --> J51[राजीव]
I31[राघोजी] --> J52[संजीव]
I31[राघोजी] --> J53[अनिल]

I32[वामन] --> J54[संतोष]

I33[सखाराम] --> J55[चंद्रकांत]
I33[सखाराम] --> J56[सूर्यकांत]
I33[सखाराम] --> J57[रमाकांत]
I33[सखाराम] --> J58[शशिकांत]

I34[सिताराम] --> J59[शामराव]

I37[शांताराम] --> J60[अशोक]
I37[शांताराम] --> J61[सुधीर]
I37[शांताराम] --> J62[संदीप]

I38[काशीराम] --> J63[राजेंद्र]
I38[काशीराम] --> J64[उमेश]

I39[आकाराम] --> J65[अमित]

I40[दत्तात्रय] --> J66[अभिषेक]

I41[सिताराम] --> J67[स्वप्निल]
I41[सिताराम] --> J68[सागर]

I42[राजाराम] --> J69[आशिष]
I42[राजाराम] --> J70[प्रशांत]
I42[राजाराम] --> J71[वैभव]

I46[रमेश] --> J72[अमोल]
I46[रमेश] --> J73[अनिकेत]


%% Generation 11
J2[किशोर] --> K1[दिव्यांक]

J3[उपेश] --> K2[गौरेश]

J4[मनोहर] --> K3[गौरव]

J6[दिनेश] --> K4[गितेश]
J6[दिनेश] --> K5[विवेक]

J8[प्रकाश] --> K6[सुशांत]
J8[प्रकाश] --> K7[विद्येश]

J14[सुशील] --> K8[यश]
J14[सुशील] --> K9[प्रणव]

J15[संतोष] --> K10[ओम]

J16[दिगंबर] --> K11[संकेत]

J18[विकास] --> K12[साईराज]

J19[प्रशांत] --> K13[रिषभ]

J24[विलास] --> K14[दिपक]

J25[प्रकाश] --> K15[प्रणव]

J27[मंदार] --> K16[आर्यन]

J28[प्रशांत] --> K17[युवांश]
J28[प्रशांत] --> K18[रुद्र]

J31[अनंत] --> K19[हर्ष]

J32[अजय] --> K20[यश]

J35[सागर] --> K21[रिद्धेश]

J36[प्रभाकर] --> K22[आनंद]
J36[प्रभाकर] --> K23[प्रशांत]

J37[रामकृष्ण] --> K24[सुदेश]

J38[श्रीकृष्ण] --> K25[हर्ष]

J39[हरिकृष्ण] --> K26[सिद्धेश]
J39[हरिकृष्ण] --> K27[ओंकार]

J40[दीपक] --> K28[अर्जुन]

J51[राजीव] --> K29[तेजस]

J52[संजीव] --> K30[सुयोग]
J52[संजीव] --> K31[विराज]

J54[संतोष] --> K32[ओमकार]

J55[चंद्रकांत] --> K33[रविकांत]
J55[चंद्रकांत] --> K34[लक्ष्मीकांत]

J57[रमाकांत] --> K35[सूर्यकांत]

J59[शामराव] --> K36[वैभव]

J60[अशोक] --> K37[अंकीत]

J63[राजेंद्र] --> K38[अमेय]

J64[उमेश] --> K39[दर्शद]

J65[अमित] --> K40[जय]
J65[अमित] --> K41[पारस]

J67[स्वप्निल] --> K42[स्वरंग]

J71[वैभव] --> K43[धैर्य]

J72[अमोल] --> K44[युग]


%% Generation 12
K5[विवेक] --> L1[अगस्त]

K6[सुशांत] --> L2[शर्विल]

K11[संकेत] --> L3[जैत्र]

K22[आनंद] --> L4[मेघ]

K23[प्रशांत] --> L5[तेज]

K24[सुदेश] --> L6[अथर्व]



%% Styling
classDef gen1 fill:#ff9999
classDef gen2 fill:#ffcc99
classDef gen3 fill:#ffff99
classDef gen4 fill:#ccff99
classDef gen5 fill:#99ffcc
classDef gen6 fill:#99ccff
classDef gen7 fill:#cc99ff
classDef gen8 fill:#ff99cc
classDef gen9 fill:#ffcccc
classDef gen10 fill:#ccffcc
classDef gen11 fill:#ccccff
classDef gen12 fill:#ffccff


class A1 gen1
class B1,B2 gen2
class C1,C2,C3,C4,C5,C6 gen3
class D1,D2,D3,D4,D5,D6,D7,D8 gen4
class E1,E2,E3,E4,E5,E6,E7 gen5
class F1,F2,F3,F4,F5,F6,F7,F8,F9,F10,F11,F12,F13 gen6
class G1,G2,G3,G4,G5,G6,G7,G8,G9,G10,G11,G12,G13,G14,G15,G16,G17,G18,G19,G20,G21,G22,G23,G24,G25 gen7
class H1,H2,H3,H4,H5,H6,H7,H8,H9,H10,H11,H12,H13,H14,H15,H16,H17,H18,H19,H20,H21,H22,H23,H24,H25,H26,H27,H28,H29,H30,H31,H32,H33,H34,H35,H36 gen8
class I1,I2,I3,I4,I5,I6,I7,I8,I9,I10,I11,I12,I13,I14,I15,I16,I17,I18,I19,I20,I21,I22,I23,I24,I25,I26,I27,I28,I29,I30,I31,I32,I33,I34,I35,I36,I37,I38,I39,I40,I41,I42,I43,I44,I45,I46,I47 gen9
class J1,J2,J3,J4,J5,J6,J7,J8,J9,J10,J11,J12,J13,J14,J15,J16,J17,J18,J19,J20,J21,J22,J23,J24,J25,J26,J27,J28,J29,J30,J31,J32,J33,J34,J35,J36,J37,J38,J39,J40,J41,J42,J43,J44,J45,J46,J47,J48,J49,J50,J51,J52,J53,J54,J55,J56,J57,J58,J59,J60,J61,J62,J63,J64,J65,J66,J67,J68,J69,J70,J71,J72,J73 gen10
class K1,K2,K3,K4,K5,K6,K7,K8,K9,K10,K11,K12,K13,K14,K15,K16,K17,K18,K19,K20,K21,K22,K23,K24,K25,K26,K27,K28,K29,K30,K31,K32,K33,K34,K35,K36,K37,K38,K39,K40,K41,K42,K43,K44 gen11
class L1,L2,L3,L4,L5 gen12